image: node:10.16.0

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - yarn install
    - yarn test
  only:
    - merge_requests

build:
  stage: build
  script:
    - yarn install
    - yarn test
    - yarn build
  only:
    - production

deploy:
  stage: deploy
  script:
    - echo "Deploying on to server"
  only:
    - production
