image: node:14.15.1

stages:
  - lint
  - test
  - build
  - deploy


eslint:
  stage: lint
  script:
    - docker build --target lint -t musicplayer-lint .
    - docker rmi musicplayer-lint
    - docker image prune -f


test:
  stage: test
  script:
    - docker build --target test -t musicplayer-test .
    - docker rmi musicplayer-test
    - docker image prune -f

dockerbuild:
  stage: build
  script:
    - docker build --target runner -t ouchie/musicplayer .
    - docker image prune -f
  only:
    - production

deploy:
  stage: deploy
  before_script:
    - echo "$token" | docker login -u "$user" --password-stdin "$CI_REGISTRY"
  script:
    - echo "Deploying on to server"
    - docker push "$repo"
  after_script:
    - docker logout
  only:
    - production
