image: node:10.16.0

stages:
  - lint
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - docker build --target test -t musicplayer-test .
    - docker rmi musicplayer-test
    - docker image prune -f
  only:
    - merge_requests

eslint:
  stage: lint
  script:
    - docker build --target lint -t musicplayer-lint .
    - docker rmi musicplayer-lint
    - docker image prune -f

dockerbuild:
  stage: build
  script:
    - docker build --target runner -t musicplayer .
    - docker image prune -f
  only:
    - production

deploy:
  stage: deploy
  script:
    - echo "Deploying on to server"
  only:
    - production
