image: node:10.16.0

stages:
  - lint
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - docker build --target test -t musicplayer-test .
    - docker rmi musicplayer-test
    - docker image prune y
  only:
    - merge_requests

eslint:
  stage: lint
  script:
    - yarn add eslint
    - yarn run lint

dockerbuild:
  stage: build
  script:
    - docker build --target runner -t musicplayer .
    - docker image prune y
  only:
    - production

deploy:
  stage: deploy
  script:
    - echo "Deploying on to server"
  only:
    - production
