image: node:10.16.0

stages:
  - test
  - build
  - deploy
  - lint

test:
  stage: test
  script:
    - yarn install
    - yarn test
  only:
    - merge_requests

eslint:
  stage: lint
  script:
    - yarn add eslint
    - yarn run lint

docker:
  stage: deploy
  script:
    - docker build . -t musicplayer

# build:
#   stage: build
#   script:
#     - yarn install
#     - yarn test
#     - yarn build
#   only:
#     - production

deploy:
  stage: deploy
  script:
    - echo "Deploying on to server"
  only:
    - production
