image: node:10.16.0

stages:
  - test
  - build

test:
  stage: test
  script:
    - yarn install
    - yarn test
  only:
    - merge_requests
  except:
    - production

build:
  stage: build
  script:
    - yarn install
    - yarn test
    - yarn build
  only:
    - production
    - merge_requests
