image: node:14.15.1

stages:
  - lint
  - test
  - build
  - deploy


eslint:
  stage: lint
  script:
    - docker login -u "$user" -p "$token" $CI_REGISTRY
    - docker build --target lint -t musicplayer-lint .
    - docker rmi musicplayer-lint
    - docker image prune -f

test:
  stage: test
  script:
    - docker build --target test -t musicplayer-test .
    - docker rmi musicplayer-test
    - docker image prune -f

dockerbuild:
  stage: build
  script:
    - docker build --target runner -t musicplayer .
    - docker image prune -f
  only:
    - production

deploy:
  stage: deploy
  before_script:
    - docker login -u "$user" -p "$token"
    - docker logout
  script:
    - echo "Deploying on to server"
  only:
    - production
